apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
  namespace: simple-time-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
        - name: app
          image: saqlainkhan/simple-time-service:latest
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
