apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-time-service
  namespace: simple-time-service
spec:
  defaultBackend:
    service:
      name: simple-time-service
      port:
        number: 80
