apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
  namespace: simple-time-service
spec:
  type: ClusterIP
  selector:
    app: simple-time-service
  ports:
    - port: 80
      targetPort: 8000
